spring:
  application:
    name: stp-client
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  port: 7003
  servlet:
    context-path: /stp-client
  error:
    include-message: always
logging:
  level:
    com.noh.stpclient.config.interceptor: DEBUG

stp:
  soap:
    msg-receiver: LPDRLALAXATS
    msg-sender: LBBCLALABXXX
  polling:
    enabled: false
    delay-ms: 55000

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  paths-to-match: /gw/**
