version: "3.1"

services:
  stp-client:
    image: 172.16.4.62:5000/noh/stp-client:dev-3671631
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      TZ: Asia/Bangkok
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "7003:7003"
    volumes:
      - "D:/lmpsLB/smart/stp-client/docker/logs:/usr/apps/logs"
      - "D:/lmpsLB/smart/stp-client/docker/config_props:/usr/apps/config_props"
      - "D:/lmpsLB/smart/stp-client/docker/key:/usr/apps/key"
    networks:
      - lbb_network

networks:
  lbb_network:
    external: true